## 一、Python基础
### 1.列表推导式与条件赋值

In [1]:
import numpy as np
import pandas as pd

In [2]:
L = []

def my_func(x):
    return 2*x
for i in range(5):
    L.append(my_func(i))
L

[0, 2, 4, 6, 8]

In [3]:
#以上写法可改写如下
[my_func(i) for i in range(5)]

[0, 2, 4, 6, 8]

In [4]:
[m+'_'+n for m in ['a','b'] for n in ['c','d']]

['a_c', 'a_d', 'b_c', 'b_d']

In [5]:
value = 'cat' if 2>1 else 'dog'
value

'cat'

In [7]:
L = [i for i in range(7)]
M = [i if i <=3 else 5 for i in L]#不能缺少else
M

[0, 1, 2, 3, 5, 5, 5]

### 2.匿名函数与map方法

In [9]:
my_func = lambda x: 2*x
my_func(3)w

6

In [10]:
plus_func = lambda a,b:a+b
plus_func(3,4)

7

In [11]:
[(lambda x:x*2)(i) for i in range(5)]

[0, 2, 4, 6, 8]

对于上述的这种列表推导式的匿名函数映射， Python 中提供了 map 函数来完成，它返回的是一个 map 对象，需要通过 list 转为列表

In [13]:
list(map(lambda x:2*x,range(5)))

[0, 2, 4, 6, 8]

In [14]:
list(map(lambda x,y:str(x)+'_'+y,range(5),list('abcde')))

['0_a', '1_b', '2_c', '3_d', '4_e']

## 3.zip对象与enumerate方法

zip函数能够把多个可迭代对象打包成一个元组构成的可迭代对象，它返回了一个 zip 对象，通过 tuple, list 可以得到相应的打包结果

In [15]:
L1,L2,L3 = list('abc'),list('def'),list('hij')
print(list(zip(L1,L2,L3)))
print(tuple(zip(L1,L2,L3)))

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]
(('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j'))


往往会在循环迭代的时候使用到 zip 函数

In [16]:
for i,j,k in zip(L1,L2,L3):
    print(i,j,k)

a d h
b e i
c f j


enumerate 是一种特殊的打包，它可以在迭代时绑定迭代元素的遍历序号

In [17]:
L = list('abcd')
for index,value in enumerate(L):
    print(index,value)

0 a
1 b
2 c
3 d


In [19]:
for index,value in zip(range(len(L)),L):
    print(index,value)

0 a
1 b
2 c
3 d


当需要对两个列表建立字典映射时，可以利用 zip 对象

In [21]:
dict(zip(L1,L2))

{'a': 'd', 'b': 'e', 'c': 'f'}

既然有了压缩函数，那么 Python 也提供了 * 操作符和 zip 联合使用来进行解压操作

In [22]:
zipped = list(zip(L1,L2,L3))
zipped

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [26]:
list(zip(*zipped))

[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]

## 二、Numpy基础
### 1.np数组的构造
#### a.等差序列（linspace,arange）

In [30]:
np.linspace(1,5,11)#起始，终止（包含），样本数

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [31]:
np.arange(1,5,2)#起始，终止（不包含），步长

array([1, 3])

#### b.特殊矩阵（zeros,ones,eye,full）

In [33]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [36]:
np.eye(3)#3*3的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(3,k=1)#偏移主对角线一个单位的伪单位矩阵

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [38]:
np.full((2,3),10)#填充单个元素

array([[10, 10, 10],
       [10, 10, 10]])

In [40]:
np.full((2,3),[1,2,3])#填充行元素

array([[1, 2, 3],
       [1, 2, 3]])

#### c.随机矩阵（random）
+ rand:0-1均匀分布的随机数组
+ randn:标准正态的随机数组
+ randint:随机整数组
+ choice：随机列表抽样
+ permutation:打散原列表

In [41]:
np.random.rand(3)

array([0.97077494, 0.83812818, 0.05082632])

In [43]:
np.random.rand(3,3)

array([[0.53275545, 0.30714173, 0.5534156 ],
       [0.4907662 , 0.54597287, 0.61980649],
       [0.85947544, 0.85332222, 0.95562186]])

对于服从区间 a 到 b 上的均匀分布可以如下生成

In [44]:
a,b = 5,15
(b - a) * np.random.rand(3) + a

array([12.19627494,  7.51420502,  7.99597996])

randn生成了N(0,I)的标准正态分布

In [47]:
np.random.randn(3)

array([-1.91587324, -0.71771066, -0.66149329])

In [48]:
np.random.randn(2,2)

array([[ 0.96874803,  0.92155609],
       [-0.80300202,  1.01592146]])

对于服从方差为$\sigma^2$均值为$\mu$的一元正态分布可以如下生成

In [50]:
sigma,mu = 2.5,3
mu + np.random.randn(3) * sigma

array([2.44184621, 0.09168844, 2.51920562])

randint 可以指定生成随机整数的最小值最大值（不包含）和维度大小

In [51]:
low,high,size = 5,15,(2,2)#生成5-14的随机整数
np.random.randint(low,high,size)

array([[11,  9],
       [14,  5]])

choice 可以从给定的列表中，以一定概率和方式抽取结果，当不指定概率时为均匀采样，默认抽取方式为有放回抽样

In [52]:
my_list = ['a','b','c','d']
np.random.choice(my_list,2,replace=False,p=[0.1,0.7,0.1,0.1])#replace为True即为无放回抽样

array(['b', 'c'], dtype='<U1')

In [54]:
np.random.choice(my_list,(3,3))#有放回抽样

array([['a', 'd', 'b'],
       ['b', 'd', 'c'],
       ['c', 'a', 'a']], dtype='<U1')

当返回的元素个数与原列表相同时，等价于使用 permutation 函数，即打散原列表

In [57]:
np.random.choice(my_list,4,replace=False)

array(['d', 'c', 'a', 'b'], dtype='<U1')

In [55]:
np.random.permutation(my_list)

array(['b', 'a', 'd', 'c'], dtype='<U1')

随机种子，它能够固定随机数的输出结果

In [58]:
np.random.seed(0)
np.random.rand()